sudo: required 
language: node_js
node_js:
    - "16"
    
services: 
    - docker
before_install: 
    - docker build -t arnoxuweichu/sample-app -f Dockerfile.dev .
script:     
    - docker run -e CI=true arnoxuweichu/sample-app npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2" ### AWS region of your choice
  app: "SampleDockerTest" ### Your EB App name
  env: "Sampledockertest-env" ### Your EB App environment name
  bucket_name: "elasticbeanstalk-ap-southeast-2-047245030703" ### S3 bucket name
  bucket_path: "EBAppTest" ### S3 folder name under S3 bucket above
  on:
    branch: main
  access_key_id: "AWS_ACCESS_KEY"
  secret_access_key: "AWS_SECRET_KEY"